// DispIDs.h: Defines a DISPID for each COM property and method we're providing.

// ITrackBar
// properties
#define DISPID_TRACKBARCTL_APPEARANCE											1
#define DISPID_TRACKBARCTL_AUTOTICKFREQUENCY							2
#define DISPID_TRACKBARCTL_AUTOTICKMARKS									3
#define DISPID_TRACKBARCTL_BACKCOLOR											4
#define DISPID_TRACKBARCTL_BORDERSTYLE										5
#define DISPID_TRACKBARCTL_CHANNELHEIGHT									6
#define DISPID_TRACKBARCTL_CHANNELLEFT										7
#define DISPID_TRACKBARCTL_CHANNELTOP											8
#define DISPID_TRACKBARCTL_CHANNELWIDTH										9
#define DISPID_TRACKBARCTL_CURRENTPOSITION								DISPID_VALUE
#define DISPID_TRACKBARCTL_DISABLEDEVENTS									10
#define DISPID_TRACKBARCTL_DONTREDRAW											11
#define DISPID_TRACKBARCTL_DOWNISLEFT											12
#define DISPID_TRACKBARCTL_ENABLED												DISPID_ENABLED
#define DISPID_TRACKBARCTL_HOVERTIME											13
#define DISPID_TRACKBARCTL_HWND														14
#define DISPID_TRACKBARCTL_HWNDBOTTOMORRIGHTBUDDY					15
#define DISPID_TRACKBARCTL_HWNDTOOLTIP										16
#define DISPID_TRACKBARCTL_HWNDTOPORLEFTBUDDY							17
#define DISPID_TRACKBARCTL_LARGESTEPWIDTH									18
#define DISPID_TRACKBARCTL_MAXIMUM												19
#define DISPID_TRACKBARCTL_MINIMUM												20
#define DISPID_TRACKBARCTL_MOUSEICON											21
#define DISPID_TRACKBARCTL_MOUSEPOINTER										22
#define DISPID_TRACKBARCTL_ORIENTATION										23
#define DISPID_TRACKBARCTL_PROCESSCONTEXTMENUKEYS					24
#define DISPID_TRACKBARCTL_RANGESELECTIONEND							25
#define DISPID_TRACKBARCTL_RANGESELECTIONSTART						26
#define DISPID_TRACKBARCTL_REGISTERFOROLEDRAGDROP					27
#define DISPID_TRACKBARCTL_REVERSED												28
#define DISPID_TRACKBARCTL_RIGHTTOLEFTLAYOUT							29
#define DISPID_TRACKBARCTL_SELECTIONTYPE									30
#define DISPID_TRACKBARCTL_SHOWSLIDER											31
#define DISPID_TRACKBARCTL_SLIDERHEIGHT										32
#define DISPID_TRACKBARCTL_SLIDERLEFT											33
#define DISPID_TRACKBARCTL_SLIDERLENGTH										34
#define DISPID_TRACKBARCTL_SLIDERTOP											35
#define DISPID_TRACKBARCTL_SLIDERWIDTH										36
#define DISPID_TRACKBARCTL_SMALLSTEPWIDTH									37
#define DISPID_TRACKBARCTL_SUPPORTOLEDRAGIMAGES						38
#define DISPID_TRACKBARCTL_TICKMARKPHYSICALPOSITION				39
#define DISPID_TRACKBARCTL_TICKMARKS											40
#define DISPID_TRACKBARCTL_TICKMARKSPOSITION							41
#define DISPID_TRACKBARCTL_TOOLTIPPOSITION								42
#define DISPID_TRACKBARCTL_VERSION												43
#define DISPID_TRACKBARCTL_BACKGROUNDDRAWMODE							46
#define DISPID_TRACKBARCTL_DETECTDOUBLECLICKS							47
// fingerprint
#define DISPID_TRACKBARCTL_APPID													500
#define DISPID_TRACKBARCTL_APPNAME												501
#define DISPID_TRACKBARCTL_APPSHORTNAME										502
#define DISPID_TRACKBARCTL_BUILD													503
#define DISPID_TRACKBARCTL_CHARSET												504
#define DISPID_TRACKBARCTL_ISRELEASE											505
#define DISPID_TRACKBARCTL_PROGRAMMER											506
#define DISPID_TRACKBARCTL_TESTER													507
// methods
#define DISPID_TRACKBARCTL_ABOUT													DISPID_ABOUTBOX
#define DISPID_TRACKBARCTL_LOADSETTINGSFROMFILE						44
#define DISPID_TRACKBARCTL_REFRESH												DISPID_REFRESH
#define DISPID_TRACKBARCTL_SAVESETTINGSTOFILE							45
#define DISPID_TRACKBARCTL_FINISHOLEDRAGDROP							48


// _ITrackBarEvents
// methods
#define DISPID_TRACKBARCTLE_CLICK													1
#define DISPID_TRACKBARCTLE_CONTEXTMENU										2
#define DISPID_TRACKBARCTLE_CUSTOMDRAW										3
#define DISPID_TRACKBARCTLE_DBLCLICK											4
#define DISPID_TRACKBARCTLE_DESTROYEDCONTROLWINDOW				5
#define DISPID_TRACKBARCTLE_GETINFOTIPTEXT								6
#define DISPID_TRACKBARCTLE_KEYDOWN												7
#define DISPID_TRACKBARCTLE_KEYPRESS											8
#define DISPID_TRACKBARCTLE_KEYUP													9
#define DISPID_TRACKBARCTLE_MCLICK												10
#define DISPID_TRACKBARCTLE_MDBLCLICK											11
#define DISPID_TRACKBARCTLE_MOUSEDOWN											12
#define DISPID_TRACKBARCTLE_MOUSEENTER										13
#define DISPID_TRACKBARCTLE_MOUSEHOVER										14
#define DISPID_TRACKBARCTLE_MOUSELEAVE										15
#define DISPID_TRACKBARCTLE_MOUSEMOVE											16
#define DISPID_TRACKBARCTLE_MOUSEUP												17
#define DISPID_TRACKBARCTLE_OLEDRAGDROP										18
#define DISPID_TRACKBARCTLE_OLEDRAGENTER									19
#define DISPID_TRACKBARCTLE_OLEDRAGLEAVE									20
#define DISPID_TRACKBARCTLE_OLEDRAGMOUSEMOVE							21
#define DISPID_TRACKBARCTLE_POSITIONCHANGED								DISPID_VALUE
#define DISPID_TRACKBARCTLE_RCLICK												22
#define DISPID_TRACKBARCTLE_RDBLCLICK											23
#define DISPID_TRACKBARCTLE_RECREATEDCONTROLWINDOW				24
#define DISPID_TRACKBARCTLE_RESIZEDCONTROLWINDOW					25
#define DISPID_TRACKBARCTLE_POSITIONCHANGING							26
#define DISPID_TRACKBARCTLE_MOUSEWHEEL										27
#define DISPID_TRACKBARCTLE_XCLICK												28
#define DISPID_TRACKBARCTLE_XDBLCLICK											29


// IOLEDataObject
// properties
// methods
#define DISPID_ODO_CLEAR																	1
#define DISPID_ODO_GETCANONICALFORMAT											2
#define DISPID_ODO_GETDATA																3
#define DISPID_ODO_GETFORMAT															4
#define DISPID_ODO_SETDATA																5
#define DISPID_ODO_GETDROPDESCRIPTION											6
#define DISPID_ODO_SETDROPDESCRIPTION											7
